config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/api/check_steam_id/:steam_id', to: 'games#check_steam_id'

  scope 'api' do
    resources :bundles
    resources :games
    resources :musictracks
    resources :drm_free_games
    resources :androidgames
    resources :ebooks
  end

end

app/models/musictrack.rb
class Musictrack < ActiveRecord::Base
  belongs_to :bundle
end

app/controllers/musictracks_controller.rb
class MusictracksController < ApplicationController
  before_action :set_musictrack, only: [:show, :edit, :update, :destroy]

  # GET /musictracks
  # GET /musictracks.json
  def index
    @musictracks = Musictrack.all
  end

  # GET /musictracks/1
  # GET /musictracks/1.json
  def show
  end

  # GET /musictracks/new
  def new
    @musictrack = Musictrack.new
  end

  # GET /musictracks/1/edit
  def edit
  end

  # POST /musictracks
  # POST /musictracks.json
  def create
    @musictrack = Musictrack.new(musictrack_params)

    respond_to do |format|
      if @musictrack.save
        format.html { redirect_to @musictrack, notice: 'Musictrack was successfully created.' }
        format.json { render :show, status: :created, location: @musictrack }
      else
        format.html { render :new }
        format.json { render json: @musictrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musictracks/1
  # PATCH/PUT /musictracks/1.json
  def update
    respond_to do |format|
      if @musictrack.update(musictrack_params)
        format.html { redirect_to @musictrack, notice: 'Musictrack was successfully updated.' }
        format.json { render :show, status: :ok, location: @musictrack }
      else
        format.html { render :edit }
        format.json { render json: @musictrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musictracks/1
  # DELETE /musictracks/1.json
  def destroy
    @musictrack.destroy
    respond_to do |format|
      format.html { redirect_to musictracks_url, notice: 'Musictrack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musictrack
      @musictrack = Musictrack.find_by_title_slug(params[:titleSlug])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musictrack_params
      params[:musictrack]
    end
end

app/helpers/musictracks_helper.rb
module MusictracksHelper
end

app/views/musictracks/_form.html.erb
<%= form_for(@musictrack, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @musictrack.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@musictrack.errors.count, "error") %> prohibited this musictrack from being saved:</h4>

      <ul>
      <% @musictrack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/musictracks/edit.html.erb
<div class="page-header">
  <%= link_to musictracks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @musictrack, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing musictrack</h1>
</div>

<%= render 'form' %>

app/views/musictracks/index.html.erb
<div class="page-header">
  <%= link_to new_musictrack_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Musictrack
  <% end %>
  <h1>Listing musictracks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @musictracks) do |musictrack| %>
            <td><%= link_to 'Show', musictrack %></td>
        <td><%= link_to 'Edit', edit_musictrack_path(musictrack) %></td>
        <td><%= link_to 'Destroy', musictrack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/musictracks/new.html.erb
<div class="page-header">
  <%= link_to musictracks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New musictrack</h1>
</div>

<%= render 'form' %>

app/views/musictracks/show.html.erb
<div class="page-header">
  <%= link_to musictracks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_musictrack_path(@musictrack), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show musictrack</h1>
</div>

<dl class="dl-horizontal">
</dl>