config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/api/check_steam_id/:steam_id', to: 'games#check_steam_id'

  scope 'api' do
    resources :bundles
    resources :games
    resources :musictracks
    resources :drm_free_games
    resources :androidgames
    resources :ebooks
  end

end

app/models/androidgame.rb
class Androidgame < ActiveRecord::Base
  belongs_to :bundle
end

app/controllers/androidgames_controller.rb
class AndroidgamesController < ApplicationController
  before_action :set_androidgame, only: [:show, :edit, :update, :destroy]

  # GET /Androidgames
  # GET /Androidgames.json
  def index
    @androidgames = Androidgame.all
  end

  # GET /Androidgames/1
  # GET /Androidgames/1.json
  def show
    @androidgame = Androidgame.find_by_title_slug(params[:titleSlug])
  end

  # GET /Androidgames/new
  def new
    @androidgame = Androidgame.new
  end

  # GET /Androidgames/1/edit
  def edit
  end

  # POST /Androidgames
  # POST /Androidgames.json
  def create
    @androidgame = Androidgame.new(androidgame_params)

    respond_to do |format|
      if @androidgame.save
        format.html { redirect_to @androidgame, notice: 'Androidgame was successfully created.' }
        format.json { render :show, status: :created, location: @androidgame }
      else
        format.html { render :new }
        format.json { render json: @androidgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Androidgames/1
  # PATCH/PUT /Androidgames/1.json
  def update
    respond_to do |format|
      if @androidgame.update(androidgame_params)
        format.html { redirect_to @androidgame, notice: 'Androidgame was successfully updated.' }
        format.json { render :show, status: :ok, location: @androidgame }
      else
        format.html { render :edit }
        format.json { render json: @androidgame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Androidgames/1
  # DELETE /Androidgames/1.json
  def destroy
    @androidgame.destroy
    respond_to do |format|
      format.html { redirect_to androidgames_url, notice: 'Androidgame was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_androidgame
      @androidgame = Androidgame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def androidgame_params
      params[:Androidgame]
    end
end

app/helpers/androidgames_helper.rb
module AndroidgamesHelper
end

app/views/androidgames/_form.html.erb
<%= form_for(@Androidgame, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @Androidgame.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@Androidgame.errors.count, "error") %> prohibited this Androidgame from being saved:</h4>

      <ul>
      <% @Androidgame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/androidgames/edit.html.erb
<div class="page-header">
  <%= link_to androidgames_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @androidgame, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Androidgame</h1>
</div>

<%= render 'form' %>

app/views/androidgames/index.html.erb
<div class="page-header">
  <%= link_to new_androidgame_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Androidgame
  <% end %>
  <h1>Listing Android games</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @adroidgames) do |androidgame| %>
            <td><%= link_to 'Show', androidgame %></td>
        <td><%= link_to 'Edit', edit_androidgame_path(androidgame) %></td>
        <td><%= link_to 'Destroy', androidgame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/androidgames/new.html.erb
<div class="page-header">
  <%= link_to Androidgames_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Androidgame</h1>
</div>

<%= render 'form' %>

app/views/androidgames/show.html.erb
<div class="page-header">
  <%= link_to Androidgames_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_Androidgame_path(@Androidgame), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Androidgame</h1>
</div>

<dl class="dl-horizontal">
</dl>