config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/api/check_steam_id/:steam_id', to: 'games#check_steam_id'

  scope 'api' do
    resources :bundles
    resources :games
    resources :musictracks
    resources :drm_free_games
    resources :androidgames
    resources :ebooks
  end

end

app/models/bundle.rb
class Bundle < ActiveRecord::Base

  validates :title, uniqueness: true

  has_many :games
  has_many :androidgames
  has_many :musictracks
  has_many :drm_free_games
  has_many :ebooks

  def unique_ebooks
    self.ebooks.select(:title).distinct
  end

  def unique_drmfree
    self.drm_free_games.select(:title).distinct
  end

  def game_keys_count
    total = 0
    self.games.each do |game|
      total += game.gamekeys.count
    end
    total
  end
end

app/controllers/bundles_controller.rb
class BundlesController < ApplicationController

  respond_to :json

  before_action :set_bundle, only: [:show, :edit, :destroy]
  before_action :set_bundle_by_id, only: :update

  # GET /bundles
  # GET /bundles.json
  def index
    @bundles = Bundle.all
  end

  # GET /bundles/1
  # GET /bundles/1.json
  def show
  end

  # GET /bundles/new
  def new
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
  end

  # POST /bundles
  # POST /bundles.json
  def create
    @bundle = Bundle.new(bundle_params)

    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundles/1
  # PATCH/PUT /bundles/1.json
  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundles/1
  # DELETE /bundles/1.json
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bundle_by_id
      @bundle = Bundle.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find_by_title_slug(params[:id])

      if @bundle.games != nil
        get_games(@bundle)
      end
    end

    def get_games(bundle)
      @games = bundle.games.sort_by { |g| g.title}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bundle_params
      params.require(:bundle).permit(:id, :title, :title_slug)
    end
end

app/helpers/bundles_helper.rb
module BundlesHelper
end

app/views/bundles/_form.html.erb
<%= form_for(@bundle, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @bundle.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@bundle.errors.count, "error") %> prohibited this bundle from being saved:</h4>

      <ul>
      <% @bundle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/bundles/edit.html.erb
<div class="page-header">
  <%= link_to bundles_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @bundle, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing bundle</h1>
</div>

<%= render 'form' %>

app/views/bundles/index.html.erb
<!--suppress HtmlUnknownAttribute -->
<div ng-controller="BundlesController">
  <div class="page-header">
    <%= link_to new_bundle_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Bundle
    <% end %>
    <h1>Bundles</h1>
  </div>

  <table class="table table-striped table-condensed table-hover">
    <thead>
    <tr>
      <th>
        <a class="glyphicon glyphicon-sort-by-alphabet" href="" ng-click="sortField = 'name'"></a>
        <a class="glyphicon glyphicon-sort-by-alphabet-alt" href="" ng-click="sortField = '-name'"></a>
        Name
        <input style="font-weight: normal" ng-model="query.name" type="text"/>
      </th>
      <th>
        <a class="glyphicon glyphicon-sort-by-alphabet" href="" ng-click="sortField = 'site'"></a>
        <a class="glyphicon glyphicon-sort-by-alphabet-alt" href="" ng-click="sortField = '-site'"></a>
        Site
        <input style="font-weight: normal" ng-model="query.site" type="text" disabled />
      </th>
      <th>
        Actions
      </th>
    </tr>
    </thead>
    <tbody>
    <tr data-ng-repeat="bundle in bundles|filter:query|orderBy:sortField">
      <td><a ng-click="viewBundle(bundle.name_slug)">{{ bundle.name }}</a></td>
      <td>{{ bundle.site }}</td>
      <td>
        <a class="btn btn-info" href="/bundle/{{bundle.name_slug}}">Show</a>
        <a class="btn btn-warning" href="/bundle/{{bundle.name_slug}}/edit">Edit</a>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/bundles/new.html.erb
<div class="page-header">
  <%= link_to bundles_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New bundle</h1>
</div>

<%= render 'form' %>

app/views/bundles/show.html.erb
<!--suppress HtmlUnknownAttribute -->
<div ng-controller="BundlesController">
  <!--suppress HtmlUnknownTarget -->
  <a href="<%= url_for(:action => 'index') %>/{{bundle.name_slug}}">{{ bundle.name }}</a>

  <pre>
    {{ bundle  }}
  </pre>
  <div class="page-header">
    <a class="btn btn-default" href="<%= url_for(:action => 'index') %>">Back <span class="glyphicon glyphicon-list-alt"></span></a>
    <a class="btn btn-primary" href="<%= url_for(:action => 'edit') %>/{{bundle.name_slug}}/edit">Edit <span class="glyphicon glyphicon-list-pencil"></span></a>
    <h1>{{ bundle.name }}</h1>
  </div>

  <dl class="dl-horizontal">
    <dt>Games</dt>
    <%= content_tag_for(:dd, @games) do |game| %>
      <% link_to game.title, game_path(game.title_slug) %>
    <% end %>
  </dl>
</div>